security:
 oauth2:
  client:
   clientId: 406306157158711
   clientSecret: b5caa4ba431c37e6875ae46901d1e0fb
   accessTokenUri: https://graph.facebook.com/oauth/access_token
   userAuthorizationUri: https://www.facebook.com/dialog/oauth
   tokenName: oauth_token
   authenticationScheme: query
   clientAuthenticationScheme: form
  resource:
   userInfoUri: https://graph.facebook.com/me
